require 'yaml'
# require 'pry'
require 'i18n'
require_relative '../entities/account'
require_relative '../entities/card'
require_relative '../entities/console'
require_relative '../entities/tax'
require_relative '../entities/withdraw_tax'
require_relative '../entities/put_tax'
require_relative '../entities/sender_tax'
require_relative '../errors/exit_error'
require_relative '../errors/wrong_card_error'
require_relative '../contracts/input'
require_relative '../contracts/statistics'
require_relative '../contracts/validators'
require_relative '../states/state'
require_relative '../states/initial'
require_relative '../states/create_account'
require_relative '../states/load_account'
require_relative '../states/delete_account'
require_relative '../states/account_menu'
require_relative '../states/show_cards'
require_relative '../states/create_card'
require_relative '../states/delete_card'
require_relative '../states/put_money'
require_relative '../states/withdraw_money'
require_relative '../states/send_money'
require_relative '../context'
require_relative '../card_factory'
require_relative '../state_factory'
require_relative '../validators/validator'
require_relative '../validators/name'
require_relative '../validators/login'
require_relative '../validators/password'
require_relative '../validators/age'

I18n.load_path << Dir[File.expand_path('config/locales') + '/*.yml']
I18n.default_locale = :en
